services:
  mysql:
    image: mysql:8.0
    container_name: asi-tp5-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: baucuenca/asi-tp5-backend:latest # Imagen del backend obtenida desde Docker Hub
    container_name: asi-tp5-backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"

volumes:
  mysql_data:
