"""Actualizacion de largo maximo para Book.title

Revision ID: 0092d758c559
Revises: 76265a9038a7
Create Date: 2025-08-15 20:26:28.609172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0092d758c559'
down_revision: Union[str, Sequence[str], None] = '76265a9038a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
