"""Agregado campo Member.is_active para implementar soft-delete

Revision ID: 2058af650c47
Revises: 8520402afd23
Create Date: 2025-08-20 00:28:21.687635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos


# revision identifiers, used by Alembic.
revision: str = '2058af650c47'
down_revision: Union[str, Sequence[str], None] = '8520402afd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'is_active')
    # ### end Alembic commands ###
