"""Creado modelo de Member

Revision ID: 24217eed5306
Revises: 0092d758c559
Create Date: 2025-08-18 14:53:16.822529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos


# revision identifiers, used by Alembic.
revision: str = '24217eed5306'
down_revision: Union[str, Sequence[str], None] = '0092d758c559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
