"""Eliminada columna Book.loaned

Revision ID: 2798fdc3f6b9
Revises: 5892d6231719
Create Date: 2025-08-20 01:50:34.246160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2798fdc3f6b9'
down_revision: Union[str, Sequence[str], None] = '5892d6231719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'loaned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('loaned', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
