"""Creado modelo de Member

Revision ID: 38553ea7754e
Revises: 0092d758c559
Create Date: 2025-08-18 15:01:57.252416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos


# revision identifiers, used by Alembic.
revision: str = '38553ea7754e'
down_revision: Union[str, Sequence[str], None] = '0092d758c559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
