"""Agregadas columnas stock, loaned y is_active a Book

Revision ID: 5892d6231719
Revises: 2058af650c47
Create Date: 2025-08-20 01:34:59.122435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos


# revision identifiers, used by Alembic.
revision: str = '5892d6231719'
down_revision: Union[str, Sequence[str], None] = '2058af650c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('loaned', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'is_active')
    op.drop_column('book', 'loaned')
    op.drop_column('book', 'stock')
    # ### end Alembic commands ###
