"""Agregada columna return a Loan

Revision ID: 8520402afd23
Revises: c91fc9835651
Create Date: 2025-08-19 22:56:57.760952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # sqlmodel no viene importado por defecto y esto genera errores de tipos de datos


# revision identifiers, used by Alembic.
revision: str = '8520402afd23'
down_revision: Union[str, Sequence[str], None] = 'c91fc9835651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('returned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'returned')
    # ### end Alembic commands ###
